# Generated by Django 2.1.4 on 2019-01-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operkassa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oper',
            name='sum_credit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='oper',
            name='sum_debet',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
