# Generated by Django 2.1.4 on 2019-01-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operkassa', '0002_auto_20190102_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oper',
            name='st_credit',
        ),
        migrations.RemoveField(
            model_name='oper',
            name='zakaz',
        ),
    ]
